### PR TITLE
Changed navigation menu title and item

### PR DESCRIPTION
**Pull request by FREDVUNI**
# Ticket No
- None

# Summary of changes
- Changed navigation title from angie to Project Zoe and menu item Chat to Connect

# How should this be tested? [Screenshots, Video or Type instructions]
- Screenshot

# Notes for reviewers
- None

# Out of scope
-  Out of scope here
Screenshot (112)

### CODE REVIEW

**Comment by FREDVUNI** [comment]
Pending reviews

**Comment by jacksono** [comment]
@FREDVUNI This PR should be raised from your branch (in your github repo) to the bootcamp-dev branch of this repo.

**Comment by FREDVUNI** [comment]
Okay

**Comment by kakoma** [comment]
Item merged with previous merge

**Pull request closed without merging**
